CREATE TABLE CLASSROOMS (
    ID_CLASSROOM INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    BUILDING VARCHAR(50) NOT NULL,
    ROOM_NUMBER VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    AREA DECIMAL(10,2) NOT NULL,
    CONSTRAINT UQ_CLASSROOM_LOCATION UNIQUE (BUILDING, ROOM_NUMBER)
);

CREATE TABLE RESPONSIBLES (
    ID_RESPONSIBLE INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(50),
    PHONE VARCHAR(15) NOT NULL,

    AGE INT NOT NULL,
    CONSTRAINT UQ_RESPONSIBLE_DETAILS UNIQUE (FULL_NAME, PHONE, AGE)
);

-- Создаем новую таблицу для связи
CREATE TABLE CLASSROOM_RESPONSIBLES (
    ID_CLASSROOM INT REFERENCES CLASSROOMS(ID_CLASSROOM),
    ID_RESPONSIBLE INT REFERENCES RESPONSIBLES(ID_RESPONSIBLE),
    PRIMARY KEY (ID_CLASSROOM, ID_RESPONSIBLE)
);