CREATE TABLE CLASSROOMS (
    ID_CLASSROOM INT PRIMARY KEY,
    BUILDING VARCHAR(50) NOT NULL,
    ROOM_NUMBER VARCHAR(10) NOT NULL,
    NAME VARCHAR(50),
    AREA DECIMAL(10,2) NOT NULL
);

CREATE TABLE RESPONSIBLES (
    ID_RESPONSIBLE INT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    AGE INT NOT NULL,
    ID_CLASSROOM INT REFERENCES CLASSROOMS(ID_CLASSROOM)
);

-- Удаляем старое поле из RESPONSIBLES (если таблица уже существует)
ALTER TABLE RESPONSIBLES DROP COLUMN ID_CLASSROOM;

-- Создаем новую таблицу для связи
CREATE TABLE CLASSROOM_RESPONSIBLES (
    ID_CLASSROOM INT REFERENCES CLASSROOMS(ID_CLASSROOM),
    ID_RESPONSIBLE INT REFERENCES RESPONSIBLES(ID_RESPONSIBLE),
    PRIMARY KEY (ID_CLASSROOM, ID_RESPONSIBLE)
);